export const Kinds = {
    Deployment: "Deployment",
    DaemonSet: "DaemonSet",
    StatefulSet: "StatefulSet",
    Job: "Job",
    CronJob: "CronJob",
    HorizontalPodAutoscaler: "HorizontalPodAutoscaler",
    Ingress: "Ingress",
    Service: "Service",
    Pod: "Pod",
    Node: "Node",
    Namespace: "Namespace",
    PersistentVolume: "PersistentVolume",
    PersistentVolumeClaim: "PersistentVolumeClaim",
    StorageClass: "StorageClass",
    ConfigMap: "ConfigMap",
    Secret: "Secret",
    ServiceAccount: "ServiceAccount",
    Role: "Role",
    RoleBinding: "RoleBinding",
    ClusterRole: "ClusterRole",
    ClusterRoleBinding: "ClusterRoleBinding",
    Endpoints: "Endpoints",
    ReplicaSet: "ReplicaSet",
    Container: "Container",
    NetworkPolicy: "NetworkPolicy",
}