apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ssd-001
  labels:
    storage-tier: ssd
    environment: production
  annotations:
    pv.kubernetes.io/provisioned-by: manual
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  mountOptions:
    - discard
    - noatime
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
    partition: 0