apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc  # PVC 名称
  namespace: default  # 可选的命名空间，默认为 default
  labels:
    app: my-app  # 用于标识和选择 PVC 的标签
    environment: production
  annotations:
    volume.beta.kubernetes.io/storage-class: "fast"  # 存储类注解（旧方式）
    description: "PVC for database storage"  # 自定义注解
spec:
  accessModes:
    - ReadWriteOnce  # 访问模式，可选值：ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  storageClassName: fast  # 存储类名称（新方式）
  volumeMode: Filesystem  # 卷模式，可选值：Filesystem（默认）, Block
  resources:
    requests:
      storage: 10Gi  # 请求的存储大小
  selector:  # 可选的选择器，用于选择特定的 PV
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev, prod]}