apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: ${NAMESPACE}
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJ...  # Base64 编码的证书
  token: LS0tLS1CRUdJ...
  namespace: LS0tLS1CRUdJ...  # Base64 编码的私钥