apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  serviceName: "nginx"
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80