apiVersion: v1
kind: Secret
metadata:
  name: my-opaque-secret
  namespace: ${NAMESPACE}
type: Opaque
data:
  username: YWRtaW4=       # "admin" 的 Base64 编码
  password: c2VjcmV0MTIz   # "secret123" 的 Base64 编码
stringData:                # 直接写明文（自动编码为 Base64）
  api-key: "abc123xyz"     # 无需手动编码