apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: ${NAMESPACE}
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4=  # "admin" 的 Base64 编码
  password: c2VjcmV0  # "secret" 的 Base64 编码