apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-report
  namespace: ${NAMESPACE}
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: report-generator
              image: report-generator:latest
              command: ["/bin/sh", "-c", "generate-report.sh"]
          restartPolicy: OnFailure