name: Release Synterix App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format (e.g. 1.0.0)'
        required: true
      release-notes:
        description: 'Markdown release notes'
        required: false
        default: ''

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install cnpm and dependencies
        run: |
          npm install -g cnpm
          cnpm install

      - name: Build Electron
        run: cnpm run build
        working-directory: ./packages/synterix-desktop
        env:
          CI: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            packages/synterix-desktop/dist/*.dmg
            packages/synterix-desktop/dist/*.exe
            packages/synterix-desktop/dist/*.AppImage
            packages/synterix-desktop/dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: electron-build-*
          merge-multiple: true

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release-notes }}
          files: |
            *.dmg
            *.exe
            *.AppImage
            *.zip
          draft: false
          prerelease: false